name: Build images

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  contents: read
  packages: write

env:
  IMAGE_TAGS: |
    type=ref,event=branch
    type=ref,event=pr
    type=ref,event=tag
    type=sha,format=long

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/base
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: base
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-ceph:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/ceph
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ceph
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}

  build-barbican:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/barbican
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: barbican
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}

  build-cinder:
    needs: build-ceph
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/cinder
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: cinder
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/ceph:sha-${{ github.sha }}

  build-glance:
    needs: build-ceph
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/glance
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: glance
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/ceph:sha-${{ github.sha }}

  build-heat:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/heat
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: heat
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}

  build-horizon:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/horizon
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: horizon
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}

  build-keystone:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/keystone
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: keystone
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}

  build-libvirt:
    needs: build-ceph
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/libvirt
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: libvirt
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/ceph:sha-${{ github.sha }}

  build-magnum:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/magnum
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: magnum
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}

  build-manila:
    needs: build-ceph
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/manila
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: manila
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/ceph:sha-${{ github.sha }}

  build-neutron:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/neutron
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: neutron
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}

  build-nova:
    needs: build-ceph
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/nova
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: nova
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/ceph:sha-${{ github.sha }}

  build-octavia:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/octavia
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: octavia
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}

  build-placement:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/ianunruh/openstack-operator-images/placement
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: placement
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=ghcr.io/ianunruh/openstack-operator-images/base:sha-${{ github.sha }}
